version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - sudo apt install maven
      - cp ./settings.xml /root/.m2/settings.xml

    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.9.0/binaries/apache-maven-3.9.0-bin.tar.gz
      - tar xzf apache-maven-3.9.0-bin.tar.gz
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/test-service.jar
